<a href="https://colab.research.google.com/github/sureshmecad/Google-Colab/blob/master/1_Interview_Questions_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) diff()

------------

#### **1) numpy.diff()**

- out[i] = arr[i+1] – arr[i]

In [3]:
# importing numpy
import numpy as np

In [1]:
# input array
arr = np.array([1, 3, 4, 7, 9])
   
print("Input array  : ", arr)
print("First order difference  : ", np.diff(arr))
print("Second order difference : ", np.diff(arr, n = 2))
print("Third order difference  : ", np.diff(arr, n = 3))

Input array  :  [1 3 4 7 9]
First order difference  :  [2 1 3 2]
Second order difference :  [-1  2 -1]
Third order difference  :  [ 3 -3]


In [2]:
# input array
arr = np.array([[1, 2, 3, 5], [4, 6, 7, 9]])
   
print("Input array  : ", arr)
print("Difference when axis is 0 : ", np.diff(arr, axis = 0))
print("Difference when axis is 1 : ", np.diff(arr, axis = 1))

Input array  :  [[1 2 3 5]
 [4 6 7 9]]
Difference when axis is 0 :  [[3 4 4 4]]
Difference when axis is 1 :  [[1 1 2]
 [2 1 2]]


#### **Question 1**

In [4]:
t = [1, 3, 6]
v = np.diff(t)
v

array([2, 3])

-------------------