<a href="https://colab.research.google.com/github/sureshmecad/Google-Colab/blob/master/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### Indexing and Slicing:
https://regenerativetoday.com/indexing-and-slicing-of-1d-2d-and-3d-arrays-using-numpy/

https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide

In [2]:
import numpy as np

### **1) Addition**

In [ ]:
# What will be the output of
np.add(1.0, 4.0) # Where np is numpy

5.0

----------------------------

### **2) Subtraction**

In [ ]:
# What will be the output of
np.subtract(1.0, 4.0) # Where np is numpy

-3.0

-----------------------------

### **3) dot Product**

#### **Syntax**

**numpy.dot(a, b, out=None)**

|Parameter   |Description                       |
|------------|----------------------------------|
|a           |[mandatory] First argument for dot product operation|
|b           |[mandatory] Second argument for dot product operation|
|out         |[optional] This argument is used for performance. This has to be a C-contiguous array, and the dtype must be the dtype that would be returned for dot(a,b).|

##### **Example 1: Numpy Dot Product of Scalars**

In [4]:
a = 3 
b = 4
output = np.dot(a,b)
print(output)

12


**Explanation**

output = a * b
       = 3 * 4
       = 12

##### **Example 2: Numpy Dot Product of 1D Arrays (Vectors)**

In [5]:
#initialize arrays
A = np.array([2, 1, 5, 4])
B = np.array([3, 4, 7, 8])

#dot product
output = np.dot(A, B)

print(output)

77


**Dot Product**

output = [2, 1, 5, 4].[3, 4, 7, 8]
       = 2*3 + 1*4 + 5*7 + 4*8
       = 77

In [3]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

##### **Example 3: Numpy Dot Product of 2-D Arrays (Matrix)**

In [ ]:
#initialize arrays
A = np.array([[2, 1], [5, 4]])
B = np.array([[3, 4], [7, 8]])

#dot product
output = np.dot(A, B)

print(output)

output

       = [[2, 1], [5, 4]].[[3, 4], [7, 8]]

       = [[2*3+1*7, 2*4+1*8], [5*3+4*7, 5*4+4*8]]

       = [[13, 16], [43, 52]]

---------------------------

### **4) Array**

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

print('\nShape of the Array:',arr.shape)

[[1 2 3 4]
 [5 6 7 8]]

Shape of the Array: (2, 4)


In [ ]:
# Python program to demonstrate 
# basic array characteristics
import numpy as np
  
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
  
# Printing type of arr object
print("Array is of type: ", type(arr))
  
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
  
# Printing shape of array
print("Shape of array: ", arr.shape)
  
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
  
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


------------------------