<a href="https://colab.research.google.com/github/sureshmecad/Google-Colab/blob/master/1_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- To create an **ndarray**, we can pass a **list, tuple or any array-like** object into the array() method, and it will be converted into an ndarray

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


#### **1) 0-D Arrays**

- **0-D arrays, or Scalars,** are the elements in an array. Each value in an array is a **0-D array.**

In [3]:
a = np.array(42)

print(a)

42


#### **2) 1-D Arrays**

- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

In [4]:
b = np.array([1, 2, 3, 4, 5])

print(b)

[1 2 3 4 5]


#### **3) 2-D Arrays**

- An array that has 1-D arrays as its elements is called a 2-D array.

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])

print(c)

[[1 2 3]
 [4 5 6]]


#### **4) 3-D arrays**

- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [6]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### **5) Check Number of Dimensions**

In [7]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### **6) Higher Dimensional Arrays**

In [9]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
shape of array : (1, 1, 1, 1, 4)


#### **7) Shape of an Array**

In [10]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


------------

In [11]:
# Python program to demonstrate 
# basic array characteristics
import numpy as np
  
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
  
# Printing type of arr object
print("Array is of type: ", type(arr))
  
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
  
# Printing shape of array
print("Shape of array: ", arr.shape)
  
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
  
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64
