<a href="https://colab.research.google.com/github/sureshmecad/Google-Colab/blob/master/2_Array_to_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- https://www.geeksforgeeks.org/create-a-dataframe-from-a-numpy-array-and-specify-the-index-column-and-column-headers/

---------------------

In [1]:
# importiong the modules
import pandas as pd
import numpy as np

In [3]:
# creating the Numpy array
array = np.array([[1, 1, 1], [2, 4, 8], [3, 9, 27], 
                  [4, 16, 64], [5, 25, 125], [6, 36, 216], 
                  [7, 49, 343]])
print(array)  
# creating a list of index names
index_values = ['first', 'second', 'third',
                'fourth', 'fifth', 'sixth', 'seventh']
   
# creating a list of column names
column_values = ['number', 'squares', 'cubes']
  
# creating the dataframe
df = pd.DataFrame(data = array, 
                  index = index_values, 
                  columns = column_values)
  
# displaying the dataframe
print(df)

[[  1   1   1]
 [  2   4   8]
 [  3   9  27]
 [  4  16  64]
 [  5  25 125]
 [  6  36 216]
 [  7  49 343]]
         number  squares  cubes
first         1        1      1
second        2        4      8
third         3        9     27
fourth        4       16     64
fifth         5       25    125
sixth         6       36    216
seventh       7       49    343


In [4]:
# creating the Numpy array
array = np.array([['Aditya', 20], ['Samruddhi', 15],
                  ['Rohan', 21], ['Anantha', 20], 
                  ['Abhinandan', 21]])
print(array)  
# creating a list of index names
index_values = ['A', 'B', 'C', 'D', 'E']
   
# creating a list of column names
column_values = ['Names', 'Age']
  
# creating the dataframe
df = pd.DataFrame(data = array, 
                  index = index_values, 
                  columns = column_values)
  
# displaying the dataframe
print(df)

[['Aditya' '20']
 ['Samruddhi' '15']
 ['Rohan' '21']
 ['Anantha' '20']
 ['Abhinandan' '21']]
        Names Age
A      Aditya  20
B   Samruddhi  15
C       Rohan  21
D     Anantha  20
E  Abhinandan  21


In [5]:
# creating the Numpy array
array = np.array([['CEO', 20, 5], ['CTO', 22, 4.5], 
                  ['CFO', 21, 3], ['CMO', 24, 2]])
  
# creating a list of index names
index_values = [1, 2, 3, 4]
   
# creating a list of column names
column_values = ['Names', 'Age', 
                 'Net worth in Millions']
  
# creating the dataframe
df = pd.DataFrame(data = array, 
                  index = index_values, 
                  columns = column_values)
  
# displaying the dataframe
print(df)

  Names Age Net worth in Millions
1   CEO  20                     5
2   CTO  22                   4.5
3   CFO  21                     3
4   CMO  24                     2
