<a href="https://colab.research.google.com/github/sureshmecad/Google-Colab/blob/master/3_NumPy_Array_Indexing_CSEPathshala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* [1) Access Array Elements](#1)

* [2) Accessing 2-D Array Elements](#2)

* [3) Accessing 3-D Array Elements](#3)

* [4) Negative Indexing](#4)

* [5) Boolean Indexing](#5)

In [1]:
import numpy as np

### **1) Access Array Elements**

- NumPy array indexing is the same as accessing array elements

- we can access an array element by refering to its index number

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc


In [2]:
arr = np.array([1,2,3,4])

print(arr[0])   # Get the first element from the following array

print(arr[1])   # Get the second element from the following array

1
2


In [3]:
# Get third and fourth elements from the following array and add them
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


### **2) Accessing 2-D Array Elements**

- To access elements from 2-D arrays we can use comma seperated integers representing the dimension and the index of the element.

- Values in a **2-D array** can be accessed using the general notation below:

       <value> = <array>[row,col]

       a = np.array([[2,3,4],[6,7,8]])
       print(a)
       value = a[1,2]
       print(value)

       [[2 3 4]
        [6 7 8]]

       8

- We can access the value **8** in the array above by calling the **row and column index [1,2]**.

- This corresponds to the **2nd row (remember row 0 is the first row)** and the **3rd column (column 0 is the first column)**

In [18]:
# Access the 2nd element on 1st dim

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [19]:
# Access the 5th element on 2nd dim

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [5]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

arr = np.array([list1, list2])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[0,0])
print(arr[0,1])
print(arr[1,0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
1
2
6


In [6]:
list1 = [1,2,3,4,5]

arr = np.array(list1)
print(arr[[1,3]])

[2 4]


### **3) Accessing 3-D Array Elements**

- To access elements from 3-D arrays we can use comma seperated integers representing the dimensions and the index of the element.

In [7]:
arr = np.array([[[1,2,3]]])
print(arr[0,0,2])

3


In [8]:
arr = np.array([[[1,2,3],[4,5,6]]])
print(arr)
print(arr[0,1,0])

[[[1 2 3]
  [4 5 6]]]
4


In [10]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [20]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


**arr[0, 1, 2] prints the value 6**

#### **And this is why:**

- The **first number** represents the **first dimension**, which contains **two arrays:**

      [[1, 2, 3], [4, 5, 6]]

      and:

      [[7, 8, 9], [10, 11, 12]]

- Since we **selected 0**, we are left with the **first array**:

      [[1, 2, 3], [4, 5, 6]]

- The **second number** represents the **second dimension**, which also contains **two arrays**:

      [1, 2, 3]

      and:

      [4, 5, 6]

- Since we **selected 1**, we are left with the **second array**:

      [4, 5, 6]

- The **third number** represents the **third dimension**, which contains **three values**:

      4

      5

      6

- Since we **selected 2**, we end up with the **third value**:

      6

### **4) Negative Indexing**

- is used to access an array from the end

In [12]:
arr = np.array([1,2,3,4,5])
print(arr[-1])

5


In [13]:
arr = np.array([[1,2,3,4,5]])
print(arr[0,-2])

4


In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


### **5) Boolean Indexing**

- In addition to use indexing to access elements in an array, there is another very cool way to access elements in a NumPy array.

In [15]:
list = [6,7,8,9,10]
arr = np.array(list)
print(arr)
print(arr>7)

[ 6  7  8  9 10]
[False False  True  True  True]


In [16]:
list = [6,7,8,9,10]
arr = np.array(list)
print(arr)
print(arr>7)
print(arr[arr>7])

[ 6  7  8  9 10]
[False False  True  True  True]
[ 8  9 10]


In [17]:
num = np.arange(20)
print(num)
odd_num = num[num % 2 == 1]
print(odd_num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### **Reference**

- https://www.youtube.com/watch?v=uqcXaSf7bG0&list=PLzx-_kRo3HZtP3tWaieUPwAh9K4I00_6p&index=3

- https://www.w3schools.com/python/numpy/numpy_array_indexing.asp